POST https://localhost:5001/api/login?useCookies=true
content-type: application/json

{
  "email": "test@test2.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/cart
content-type: application/json

{
  "id": "cart1",
  "items": [
    {
      "productId": 17,
      "productName": "Angular Purple Boots",
      "price": 1,
      "quantity": 3,
      "pictureUrl": "/images/products/boot-ang2.png",
      "brand": "Angular",
      "type": "Boots"
    }
  ]
}

###

POST https://localhost:5001/api/payments/cart1
content-type: application/json

{}

###

POST https://localhost:5001/api/orders
content-type: application/json

{
  "cartId": "cart1",
  "deliveryMethodId": 1,
  "shippingAddress": {
    "name": "Tom Smith",
    "city": "New York",
    "country": "US",
    "line1": "100 Centre Street",
    "line2": null,
    "postalCode": "10013",
    "state": "NY"
  },
  "paymentSummary": {
    "brand": "Mastercard",
    "last4": "4444",
    "expMonth": 12,
    "expYear": 2027
  }
}

###

GET https://localhost:5001/api/orders

###

GET https://localhost:5001/api/orders/1