GET https://localhost:5001

###

GET https://localhost:5001/weatherforecast

###

POST https://localhost:5001/api/products
content-type: application/json

{
  "name":"Product 2",
  "description": "Description product 2",
  "price": 34.23,
  "pictureUrl": "https://media.istockphoto.com/id/1455397163/es/foto/retrato-de-una-chica-india-oscura-bonita.webp?s=2048x2048&w=is&k=20&c=1hIi_71ep7mIQhUV_8d97alkfmLzN3t6gjerOB7rwNM=",
  "type": "any type 2",
  "brand": "any brand 2",
  "quantityInStock": 40

}


###

POST https://localhost:5001/api/products
content-type: application/json

{
  "name":"Product 3",
  "description": "Description product 3",
  "price": 44.23,
  "pictureUrl": "https://media.istockphoto.com/id/1455397163/es/foto/retrato-de-una-chica-india-oscura-bonita.webp?s=2048x2048&w=is&k=20&c=1hIi_71ep7mIQhUV_8d97alkfmLzN3t6gjerOB7rwNM=",
  "type": "any type 2",
  "brand": "any brand 2",
  "quantityInStock": 56

}


###

GET https://localhost:5001/api/products


###
PUT https://localhost:5001/api/products/2003
content-type: application/json

{
  "id": 2003,
  "name":"Prod 2003 Upd",
  "description": "Desc product 2 Was changed",
  "authors": "Lorem Ipsum",
  "price": 56.33,
  "pictureUrl": "https://media.istockphoto.com/id/1455397163/es/foto/retrato-de-una-chica-india-oscura-bonita.webp?s=2048x2048&w=is&k=20&c=1hIi_71ep7mIQhUV_8d97alkfmLzN3t6gjerOB7rwNM=",
  "type": "any type 2",
  "brand": "any brand 2",
  "quantityInStock": 40
}


###

POST https://localhost:5001/api/products
content-type: application/json

{
  "name":"Product Delete ME",
  "description": "Description product 3",
  "price": 44.23,
  "pictureUrl": "https://media.istockphoto.com/id/1455397163/es/foto/retrato-de-una-chica-india-oscura-bonita.webp?s=2048x2048&w=is&k=20&c=1hIi_71ep7mIQhUV_8d97alkfmLzN3t6gjerOB7rwNM=",
  "type": "any type 2",
  "brand": "any brand 2",
  "quantityInStock": 56
}


###

DELETE https://localhost:5001/api/products/2004


###

GET https://localhost:5001/api/products/brands


###

GET https://localhost:5001/api/products/types


###

GET https://localhost:5001/api/products?brand=React

###

GET https://localhost:5001/api/products?type=Hats


###

GET https://localhost:5001/api/products

###

GET https://localhost:5001/api/products?sort=priceDesc


###

GET https://localhost:5001/api/products?sort=priceAsc

###

GET https://localhost:5001/api/products?pageSize=3&pageIndex=1

###

GET https://localhost:5001/api/products?pageSize=3&pageIndex=1&types=boards

###

GET https://localhost:5001/api/products?search=red

###

GET https://localhost:5001/api/products?search=purple