
POST https://localhost:5001/api/login?useCookies=true
content-type: application/json

{
  "email": "test@test2.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/cart
content-type: application/json

{
  "id": "cart1",
  "items": [
    {
      "productName":"Angular Blue Boots",
      "price": 34.23,
      "pictureUrl": "/images/products/boot-ang1.png",
      "type": "Boots",
      "brand": "Angular",
      "productId": 18,
      "quantity": 3
    }
  ]
}

###

POST https://localhost:5001/api/payments/cart1
content-type: application/json

{}

###

POST https://localhost:5001/api/cart
content-type: application/json

{
  "id": "cart1",
  "items": [
    {
      "productName":"Angular Blue Boots",
      "price": 34.23,
      "pictureUrl": "/images/products/boot-ang1.png",
      "type": "Boots",
      "brand": "Angular",
      "productId": 18,
      "quantity": 3
    }
  ],
  "deliveryMethodId": null,
  "clientSecret": "pi_3Qbtz5IkTuFXoxEt0rOvxMnQ_secret_IHXGqxveMoQic9ZFsoz95bokq",
  "paymentIntentId": "pi_3Qbtz5IkTuFXoxEt0rOvxMnQ"
}