###

GET https://localhost:5001/api/buggy/notfound

###

GET https://localhost:5001/api/buggy/badrequest


###

GET https://localhost:5001/api/buggy/unathorized

###

GET https://localhost:5001/api/buggy/internalerror


###

POST https://localhost:5001/api/buggy/validationerror
content-type: application/json

{
  "name": "My Product"
}