POST https://localhost:5001/api/register
content-type: application/json

{
  "firstName": "Walter",
  "lastName": "Doe",
  "email": "walterdoet@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/register
content-type: application/json

{
  "firstName": "Tom",
  "lastName": "Smith",
  "email": "tomsmith@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/register
content-type: application/json

{
  "firstName": "Tom",
  "lastName": "Smith",
  "email": "test@test3.com",
  "password": "letmein"
}

###

POST https://localhost:5001/api/register
content-type: application/json

{
  "firstName": "Tom",
  "lastName": "Smith",
  "email": "test@test3.com",
  "password": "letmein"
}

###

POST https://localhost:5001/register
content-type: application/json

{
  "email": "test@test4.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/login
content-type: application/json

{
  "email": "johndoe@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/login?useCookies=true
content-type: application/json

{
  "email": "johndoe@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/login
content-type: application/json

{
  "email": "test@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/login?useCookies=true
content-type: application/json

{
  "email": "test@test.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/login?useCookies=true
content-type: application/json

{
  "email": "test@test4.com",
  "password": "Pa$$w0rd"
}

###

POST https://localhost:5001/api/account/address
content-type: application/json

{
 "line1": "10 the Street",
 "city": "New York",
 "state": "NY",
 "postalCode": "398487",
 "country": " USA"
}

###

GET https://localhost:5001/api/account/user-info

###

POST https://localhost:5001/api/logout
content-type: application/json

{}

###

POST https://localhost:5001/api/account/logout
content-type: application/json

{}


### 

GET https://localhost:5001/api/buggy/secret
cookie: "wewer"

